name: create-deployments
on: [workflow_dispatch]
permissions:
  contents: read
  pages: write
  id-token: write
concurrency:
  group: "pages"
  cancel-in-progress: true
jobs:
  build:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Main
        uses: actions/checkout@v4
        with:
          path: main
      - name: Checkout Target repository
        uses: actions/checkout@v4
        with:
          repository: ShotaOki/iot-app-kit-extra
          path: iot-app-kit-extra
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.17.1"
      - name: Build package
        working-directory: iot-app-kit-extra/src/scene_composer_extra
        run: |
          npm install --legacy-peer-deps
          npm run build:wsl
      - name: Build modules
        working-directory: iot-app-kit-extra/src/scene_composer_extra
        run: |
          npm install --legacy-peer-deps
          npm run build:wsl
      - name: Dependency to current repository
        working-directory: iot-app-kit-extra/examples/typescript-simple
        run: |
          sed -i 's/"@iak-extra\/scene-composer-extra.*$/"@iak-extra\/scene-composer-extra": "file:..\/..\/package\/scene_composer_extra",/g' package.json
          npm install --legacy-peer-deps
          npm run build
        env:
          PUBLIC_URL: /Example_App
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        working-directory: iot-app-kit-extra/examples/typescript-simple
        with:
          path: "./build"

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
